
package webserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServer", targetNamespace = "http://webserver/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServer {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webserver/WebServer/pairInRequest", output = "http://webserver/WebServer/pairInResponse")
    public void pairIn(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        Task arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webserver/WebServer/pairOutRequest", output = "http://webserver/WebServer/pairOutResponse")
    public void pairOut(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webserver.Task
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserver/WebServer/readPairRequest", output = "http://webserver/WebServer/readPairResponse")
    public Task readPair(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://webserver/WebServer/printQueueRequest", output = "http://webserver/WebServer/printQueueResponse")
    public void printQueue();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webserver/WebServer/sendTaskResultRequest", output = "http://webserver/WebServer/sendTaskResultResponse")
    public void sendTaskResult(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserver/WebServer/getResultTaskRequest", output = "http://webserver/WebServer/getResultTaskResponse")
    public int getResultTask(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
